package com.anilemrah.dolap.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "productType")
public class ProductType {
	@DynamoDBHashKey(attributeName = "productTypeId")
	@DynamoDBAutoGeneratedKey
	private String productTypeId;
	@DynamoDBAttribute(attributeName = "productTypeName")
	private String productTypeName;

	public String getProductTypeId() {
		return productTypeId;
	}

	public void setProductTypeId(String productTypeId) {
		this.productTypeId = productTypeId;
	}

	public String getProductTypeName() {
		return productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	/**
	 * Constructor for DynamoDB queries, builder pattern maybe used in the future
	 * 
	 * @param id
	 */
	public ProductType(String productTypeId) {
		this.productTypeId = productTypeId;
	}

	public ProductType() {
	}

	@Override
	public String toString() {
		return "ProductType [productTypeId=" + productTypeId + ", productTypeName=" + productTypeName + "]";
	}
}